g <- make_empty_graph() +
	vertices('BostonComp', 'Vancouver', 'Tanks', 'Calgary', 'Chicago', 'DragonTigers', 'BostonRec', 
	'Wolfpack', 'Trillium', 'Reloaded', 'Goodfellas', 'NYBodega', 'NYJaywalkers', 'BlackTans')
games <- paste0('Game', 1:29)
g <- add_vertices(g, 29, name=games)

g <- g + edge('BostonComp', 'Game1', color='grey')
g <- g + edge('Vancouver', 'Game1', color='grey')
g <- g + edge('Tanks', 'Game2', color='grey')
g <- g + edge('Calgary', 'Game2', color='grey')
g <- g + edge('Chicago', 'Game3', color='grey')
g <- g + edge('DragonTigers', 'Game3', color='grey')
g <- g + edge('BostonRec', 'Game4', color='grey')
g <- g + edge('Wolfpack', 'Game4', color='grey')
g <- g + edge('Trillium', 'Game5', color='grey')
g <- g + edge('Reloaded', 'Game5', color='grey')
g <- g + edge('Goodfellas', 'Game6', color='grey')
g <- g + edge('NYBodega', 'Game6', color='grey')
g <- g + edge('Game1', 'Game7', color='red')
g <- g + edge('Game2', 'Game7', color='blue')
g <- g + edge('Game5', 'Game8', color='red')
g <- g + edge('Game3', 'Game8', color='blue')
g <- g + edge('NYJaywalkers', 'Game9', color='grey')
g <- g + edge('Game2', 'Game9', color='red')
g <- g + edge('Game3', 'Game10', color='red')
g <- g + edge('BlackTans', 'Game10', color='grey')
g <- g + edge('Game5', 'Game11', color='blue')
g <- g + edge('Game7', 'Game11', color='blue')
g <- g + edge('Game8', 'Game12', color='blue')
g <- g + edge('Game1', 'Game12', color='blue')
g <- g + edge('Game9', 'Game13', color='red')
g <- g + edge('Game6', 'Game13', color='red')
g <- g + edge('Game10', 'Game14', color='red')
g <- g + edge('Game4', 'Game14', color='red')
g <- g + edge('Game9', 'Game15', color='blue')
g <- g + edge('Game4', 'Game15', color='blue')
g <- g + edge('Game6', 'Game16', color='blue')
g <- g + edge('Game10', 'Game16', color='blue')
g <- g + edge('Game12', 'Game17', color='blue')
g <- g + edge('Game11', 'Game17', color='red')
g <- g + edge('Game11', 'Game18', color='blue')
g <- g + edge('Game12', 'Game18', color='red')
g <- g + edge('Game13', 'Game19', color='red')
g <- g + edge('Game14', 'Game19', color='red')
g <- g + edge('Game16', 'Game20', color='red')
g <- g + edge('Game13', 'Game20', color='blue')
g <- g + edge('Game14', 'Game21', color='blue')
g <- g + edge('Game15', 'Game21', color='red')
g <- g + edge('Game8', 'Game22', color='red')
g <- g + edge('Game15', 'Game22', color='blue')
g <- g + edge('Game16', 'Game23', color='blue')
g <- g + edge('Game7', 'Game23', color='red')
g <- g + edge('Game17', 'Game24', color='red')
g <- g + edge('Game18', 'Game24', color='red')
g <- g + edge('Game22', 'Game25', color='red')
g <- g + edge('Game23', 'Game25', color='red')
g <- g + edge('Game17', 'Game26', color='blue')
g <- g + edge('Game18', 'Game26', color='blue')
g <- g + edge('Game22', 'Game27', color='blue')
g <- g + edge('Game23', 'Game27', color='blue')
g <- g + edge('Game20', 'Game28', color='red')
g <- g + edge('Game21', 'Game28', color='red')
g <- g + edge('Game20', 'Game29', color='blue')
g <- g + edge('Game21', 'Game29', color='blue')

V(g)$label.color <- 'black'
V(g)$label.color[1:14] <- 'grey'
V(g)$shape <- 'none'

pdf('~/CoupeCanadaCup_Graphs.pdf', width=10, height=10)
plot(g, edge.arrow.size=0.5, layout=layout_with_gem(g))
legend('topright', legend=c('win','loss'), fill=c('blue','red'))
plot(g, edge.arrow.size=0.5, layout=layout_with_kk(g))
legend('topright', legend=c('win','loss'), fill=c('blue','red'))
plot(g, edge.arrow.size=0.5, layout=layout_on_grid(g))
legend('topright', legend=c('win','loss'), fill=c('blue','red'))
dev.off()
